/*
 * Copyright 2026 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  ANNOTATION_LOCATION,
  ANNOTATION_ORIGIN_LOCATION,
} from '@backstage/catalog-model';
import {
  coreServices,
  createBackendModule,
} from '@backstage/backend-plugin-api';
import type { DeferredEntity } from '@backstage/plugin-catalog-node';
import {
  IncrementalEntityProvider,
  incrementalIngestionProvidersExtensionPoint,
} from '@backstage/plugin-catalog-backend-module-incremental-ingestion';

interface Cursor {
  page: number;
}

interface Context {
  providerName: string;
}

/**
 * Generates mock service entities for testing incremental ingestion.
 */
function generateMockEntities(
  providerName: string,
  page: number,
  itemsPerPage: number = 5,
): DeferredEntity[] {
  const entities: DeferredEntity[] = [];
  const startIndex = (page - 1) * itemsPerPage;

  for (let i = 0; i < itemsPerPage; i++) {
    const index = startIndex + i;
    const serviceName = `test-service-${index + 1}`;
    const location = `${providerName}:${serviceName}`;

    entities.push({
      entity: {
        apiVersion: 'backstage.io/v1beta1',
        kind: 'Component',
        metadata: {
          name: serviceName,
          description: `Test service #${
            index + 1
          } generated by ${providerName}`,
          annotations: {
            [ANNOTATION_LOCATION]: location,
            [ANNOTATION_ORIGIN_LOCATION]: location,
          },
          tags: ['test', 'incremental'],
        },
        spec: {
          type: 'service',
          lifecycle: 'production',
          owner: 'team-a',
        },
      },
    });
  }

  return entities;
}

/**
 * Test incremental entity provider that generates mock services.
 * Useful for testing the incremental ingestion UI.
 */
export const testIncrementalProvider = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'test-incremental-provider',
  register(reg) {
    reg.registerInit({
      deps: {
        logger: coreServices.logger,
        providers: incrementalIngestionProvidersExtensionPoint,
      },
      async init({ logger, providers }) {
        const providerName = 'test-incremental-provider';
        const totalPages = 10; // Generate 10 pages of entities (50 total with 5 per page)
        const itemsPerPage = 5;

        const provider: IncrementalEntityProvider<Cursor, Context> = {
          getProviderName: () => providerName,

          around: async burst => {
            logger.info(
              `[${providerName}] Starting ingestion cycle - will generate ${totalPages} pages`,
            );
            await burst({ providerName });
            logger.info(`[${providerName}] Ingestion cycle complete`);
          },

          next: async (context, cursor) => {
            const currentPage = cursor?.page ?? 1;
            const { providerName: name } = context;

            // Simulate some processing time
            await new Promise(resolve => setTimeout(resolve, 600));

            logger.info(
              `[${name}] Fetching page ${currentPage} of ${totalPages}`,
            );

            const entities = generateMockEntities(
              name,
              currentPage,
              itemsPerPage,
            );

            const done = currentPage >= totalPages;

            if (done) {
              logger.info(
                `[${name}] All pages fetched. Generated ${
                  totalPages * itemsPerPage
                } entities total.`,
              );
              return {
                done: true as const,
                entities,
              };
            }

            const nextCursor: Cursor = { page: currentPage + 1 };

            return {
              done: false as const,
              entities,
              cursor: nextCursor,
            };
          },
        };

        providers.addProvider({
          provider: provider,
          options: {
            // Wait 5 seconds between bursts
            burstInterval: { seconds: 5 },
            // Each burst can run for up to 30 seconds
            burstLength: { seconds: 30 },
            // Rest for 60 seconds after completing all pages
            restLength: { seconds: 60 },
          },
        });

        logger.info(
          `[${providerName}] Test incremental provider registered. Will generate ${
            totalPages * itemsPerPage
          } mock entities.`,
        );
      },
    });
  },
});

export const testIncrementalProviderTwo = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'test-incremental-provider-two',
  register(reg) {
    reg.registerInit({
      deps: {
        logger: coreServices.logger,
        providers: incrementalIngestionProvidersExtensionPoint,
      },
      async init({ logger, providers }) {
        const providerName = 'test-incremental-provider-two';
        const totalPages = 10; // Generate 10 pages of entities (50 total with 5 per page)
        const itemsPerPage = 5;

        const provider: IncrementalEntityProvider<Cursor, Context> = {
          getProviderName: () => providerName,

          around: async burst => {
            logger.info(
              `[${providerName}] Starting ingestion cycle - will generate ${totalPages} pages`,
            );
            await burst({ providerName });
            logger.info(`[${providerName}] Ingestion cycle complete`);
          },

          next: async (context, cursor) => {
            const currentPage = cursor?.page ?? 1;
            const { providerName: name } = context;

            // Simulate some processing time
            await new Promise(resolve => setTimeout(resolve, 600));

            logger.info(
              `[${name}] Fetching page ${currentPage} of ${totalPages}`,
            );

            const entities = generateMockEntities(
              name,
              currentPage,
              itemsPerPage,
            );

            const done = currentPage >= totalPages;

            if (done) {
              logger.info(
                `[${name}] All pages fetched. Generated ${
                  totalPages * itemsPerPage
                } entities total.`,
              );
              return {
                done: true as const,
                entities,
              };
            }

            const nextCursor: Cursor = { page: currentPage + 1 };

            return {
              done: false as const,
              entities,
              cursor: nextCursor,
            };
          },
        };

        providers.addProvider({
          provider: provider,
          options: {
            // Wait 5 seconds between bursts
            burstInterval: { seconds: 5 },
            // Each burst can run for up to 30 seconds
            burstLength: { seconds: 30 },
            // Rest for 60 seconds after completing all pages
            restLength: { seconds: 60 },
          },
        });

        logger.info(
          `[${providerName}] Test incremental provider registered. Will generate ${
            totalPages * itemsPerPage
          } mock entities.`,
        );
      },
    });
  },
});
